# Generated by Django 3.1 on 2021-04-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE IF NOT EXISTS ov.companies (
        cin bigint primary key,
        name character varying,
        br_section character varying,
        address_line character varying,
        last_update timestamp without time zone,         
        created_at timestamp without time zone,
        updated_at timestamp without time zone);"""),
        
        migrations.RunSQL("""INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
        SELECT cin, corporate_body_name, br_section, address_line, updated_at, now(), now()
        FROM (SELECT cin, corporate_body_name, br_section, address_line, updated_at, 
        MAX(updated_at) OVER(PARTITION BY cin) as najaktualnejsi_datum
        FROM ov.or_podanie_issues) x
        WHERE updated_at = najaktualnejsi_datum and cin is not null;"""),
        
        
        migrations.RunSQL("""INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
        SELECT cin, corporate_body_name, br_section, "address_line", updated_at, now(), now()
        FROM (SELECT cin, corporate_body_name, br_section, street, postal_code, city, updated_at, 
            concat(street, ' ', postal_code, ' ', city) "address_line",
        MAX(updated_at) OVER(PARTITION BY cin) as najaktualnejsi_datum
        FROM ov.likvidator_issues) x
        WHERE updated_at = najaktualnejsi_datum and cin is not null
        ON CONFLICT(cin) DO NOTHING;"""),
        
        migrations.RunSQL("""INSERT INTO ov.companies(cin, name, address_line, last_update, created_at, updated_at)
        SELECT cin, corporate_body_name, "address_line", updated_at, now(), now()
        FROM (SELECT cin, corporate_body_name, street, postal_code, city, updated_at, 
            concat(street, ' ', postal_code, ' ', city) "address_line",
        MAX(updated_at) OVER(PARTITION BY cin) as najaktualnejsi_datum
        FROM ov.konkurz_vyrovnanie_issues) x
        WHERE updated_at = najaktualnejsi_datum and cin is not null
        ON CONFLICT(cin) DO NOTHING;"""),
        
        migrations.RunSQL("""INSERT INTO ov.companies(cin, name, br_section, address_line, last_update, created_at, updated_at)
        SELECT cin, corporate_body_name, br_section, "address_line", updated_at, now(), now()
        FROM (SELECT cin, corporate_body_name, br_section, street, postal_code, city, updated_at, 
            concat(street, ' ', postal_code, ' ', city) "address_line",
        MAX(updated_at) OVER(PARTITION BY cin) as najaktualnejsi_datum
        FROM ov.znizenie_imania_issues) x
        WHERE updated_at = najaktualnejsi_datum and cin is not null
        ON CONFLICT(cin) DO NOTHING;"""),
        
        migrations.RunSQL("""INSERT INTO ov.companies(cin, name, address_line, last_update, created_at, updated_at)
        SELECT cin, corporate_body_name, "address_line", updated_at, now(), now()
        FROM (SELECT cin, corporate_body_name, street, postal_code, city, updated_at, 
            concat(street, ' ', postal_code, ' ', city) "address_line",
        MAX(updated_at) OVER(PARTITION BY cin) as najaktualnejsi_datum
        FROM ov.konkurz_restrukturalizacia_actors) x
        WHERE updated_at = najaktualnejsi_datum and cin is not null
        ON CONFLICT(cin) DO NOTHING;"""),
        
        migrations.RunSQL("""ALTER TABLE ov.or_podanie_issues ADD COLUMN company_id BIGINT;"""),
        migrations.RunSQL("""ALTER TABLE ov.likvidator_issues ADD COLUMN company_id BIGINT;"""),
        migrations.RunSQL("""ALTER TABLE ov.konkurz_vyrovnanie_issues ADD COLUMN company_id BIGINT;"""),
        migrations.RunSQL("""ALTER TABLE ov.znizenie_imania_issues ADD COLUMN company_id BIGINT;"""),
        migrations.RunSQL("""ALTER TABLE ov.konkurz_restrukturalizacia_actors ADD COLUMN company_id BIGINT;"""),
        
        migrations.RunSQL("""ALTER TABLE ov.or_podanie_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"""),
        migrations.RunSQL("""UPDATE ov.or_podanie_issues SET company_id = cin;"""),

        migrations.RunSQL("""ALTER TABLE ov.likvidator_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"""),
        migrations.RunSQL("""UPDATE ov.likvidator_issues SET company_id = cin;"""),

        migrations.RunSQL("""ALTER TABLE ov.konkurz_vyrovnanie_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"""),
        migrations.RunSQL("""UPDATE ov.konkurz_vyrovnanie_issues SET company_id = cin;"""),

        migrations.RunSQL("""ALTER TABLE ov.znizenie_imania_issues ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"""),
        migrations.RunSQL("""UPDATE ov.znizenie_imania_issues SET company_id = cin;"""),

        migrations.RunSQL("""ALTER TABLE ov.konkurz_restrukturalizacia_actors ADD FOREIGN KEY (company_id) REFERENCES ov.companies(cin);"""),
        migrations.RunSQL("""UPDATE ov.konkurz_restrukturalizacia_actors SET company_id = cin;"""),
        
    ]
